# docker-compose.yml
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50001:50000
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - ./jenkins/var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/usr/local/bin/docker:/usr/local/bin/docker